# Generated by Django 5.2.3 on 2025-07-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230602_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='no_telpon',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pendidikan_terakhir',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='kk',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nik',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
