# Generated by Django 5.2.3 on 2025-07-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_profile_jurusan_remove_profile_no_telpon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticated_Crypted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_verified', models.CharField(blank=True, max_length=255, null=True)),
                ('crypted_verified', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_identities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
