# Generated by Django 5.2.3 on 2025-07-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_authenticated_crypted_profile_verified_identities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authenticated_Crypted',
        ),
    ]
