# Generated by Django 5.2.3 on 2025-07-05 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rekening', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_type', models.IntegerField(choices=[(0, 'AED - UAE Dirham'), (1, 'AFN - Afghani'), (2, 'ALL - Lek'), (3, 'AMD - Armenian Dram'), (4, 'ANG - Netherlands Antillean Guilder'), (5, 'AOA - Kwanza'), (6, 'ARS - Argentine Peso'), (7, 'AUD - Australian Dollar'), (8, 'AWG - Aruban Florin'), (9, 'AZN - Azerbaijanian Manat'), (10, 'BAM - Convertible Mark'), (11, 'BBD - Barbados Dollar'), (12, 'BDT - Taka'), (13, 'BGN - Bulgarian Lev'), (14, 'BHD - Bahraini Dinar'), (15, 'BIF - Burundi Franc'), (16, 'BMD - Bermudian Dollar'), (17, 'BND - Brunei Dollar'), (18, 'BOB - Boliviano'), (19, 'BRL - Brazilian Real'), (20, 'BSD - Bahamian Dollar'), (21, 'BTN - Ngultrum'), (22, 'BWP - Pula'), (23, 'BYN - Belarusian Ruble'), (24, 'BZD - Belize Dollar'), (25, 'CAD - Canadian Dollar'), (26, 'CDF - Congolese Franc'), (27, 'CHF - Swiss Franc'), (28, 'CLP - Chilean Peso'), (29, 'CNY - Yuan Renminbi'), (30, 'COP - Colombian Peso'), (31, 'CRC - Costa Rican Colon'), (32, 'CUC - Peso Convertible'), (33, 'CUP - Cuban Peso'), (34, 'CVE - Cabo Verde Escudo'), (35, 'CZK - Czech Koruna'), (36, 'DJF - Djibouti Franc'), (37, 'DKK - Danish Krone'), (38, 'DOP - Dominican Peso'), (39, 'DZD - Algerian Dinar'), (40, 'EGP - Egyptian Pound'), (41, 'ERN - Nakfa'), (42, 'ETB - Ethiopian Birr'), (43, 'EUR - Euro'), (44, 'FJD - Fiji Dollar'), (45, 'FKP - Falkland Islands Pound'), (46, 'FOK - Faroese Króna'), (47, 'GBP - Pound Sterling'), (48, 'GEL - Lari'), (49, 'GGP - Guernsey Pound'), (50, 'GHS - Ghana Cedi'), (51, 'GIP - Gibraltar Pound'), (52, 'GMD - Dalasi'), (53, 'GNF - Guinean Franc'), (54, 'GTQ - Quetzal'), (55, 'GYD - Guyana Dollar'), (56, 'HKD - Hong Kong Dollar'), (57, 'HNL - Lempira'), (58, 'HRK - Croatian Kuna'), (59, 'HTG - Gourde'), (60, 'HUF - Forint'), (61, 'IDR - Rupiah'), (62, 'ILS - New Israeli Sheqel'), (63, 'IMP - Isle of Man Pound'), (64, 'INR - Indian Rupee'), (65, 'IQD - Iraqi Dinar'), (66, 'IRR - Iranian Rial'), (67, 'ISK - Iceland Krona'), (68, 'JEP - Jersey Pound'), (69, 'JMD - Jamaican Dollar'), (70, 'JOD - Jordanian Dinar'), (71, 'JPY - Yen'), (72, 'KES - Kenyan Shilling'), (73, 'KGS - Som'), (74, 'KHR - Riel'), (75, 'KID - Kiribati Dollar'), (76, 'KMF - Comorian Franc'), (77, 'KRW - Won'), (78, 'KWD - Kuwaiti Dinar'), (79, 'KYD - Cayman Islands Dollar'), (80, 'KZT - Tenge'), (81, 'LAK - Lao Kip'), (82, 'LBP - Lebanese Pound'), (83, 'LKR - Sri Lanka Rupee'), (84, 'LRD - Liberian Dollar'), (85, 'LSL - Loti'), (86, 'LYD - Libyan Dinar'), (87, 'MAD - Moroccan Dirham'), (88, 'MDL - Moldovan Leu'), (89, 'MGA - Malagasy Ariary'), (90, 'MKD - Denar'), (91, 'MMK - Kyat'), (92, 'MNT - Tugrik'), (93, 'MOP - Pataca'), (94, 'MRU - Ouguiya'), (95, 'MUR - Mauritius Rupee'), (96, 'MVR - Rufiyaa'), (97, 'MWK - Malawi Kwacha'), (98, 'MXN - Mexican Peso'), (99, 'MYR - Malaysian Ringgit'), (100, 'MZN - Mozambique Metical'), (101, 'NAD - Namibia Dollar'), (102, 'NGN - Naira'), (103, 'NIO - Cordoba Oro'), (104, 'NOK - Norwegian Krone'), (105, 'NPR - Nepalese Rupee'), (106, 'NZD - New Zealand Dollar'), (107, 'OMR - Rial Omani'), (108, 'PAB - Balboa'), (109, 'PEN - Sol'), (110, 'PGK - Kina'), (111, 'PHP - Philippine Peso'), (112, 'PKR - Pakistan Rupee'), (113, 'PLN - Zloty'), (114, 'PYG - Guarani'), (115, 'QAR - Qatari Rial'), (116, 'RON - Romanian Leu'), (117, 'RSD - Serbian Dinar'), (118, 'RUB - Russian Ruble'), (119, 'RWF - Rwanda Franc'), (120, 'SAR - Saudi Riyal'), (121, 'SBD - Solomon Islands Dollar'), (122, 'SCR - Seychelles Rupee'), (123, 'SDG - Sudanese Pound'), (124, 'SEK - Swedish Krona'), (125, 'SGD - Singapore Dollar'), (126, 'SHP - Saint Helena Pound'), (127, 'SLL - Leone'), (128, 'SOS - Somali Shilling'), (129, 'SRD - Surinam Dollar'), (130, 'SSP - South Sudanese Pound'), (131, 'STN - Dobra'), (132, 'SYP - Syrian Pound'), (133, 'SZL - Lilangeni'), (134, 'THB - Baht'), (135, 'TJS - Somoni'), (136, 'TMT - Turkmenistan New Manat'), (137, 'TND - Tunisian Dinar'), (138, 'TOP - Pa’anga'), (139, 'TRY - Turkish Lira'), (140, 'TTD - Trinidad and Tobago Dollar'), (141, 'TVD - Tuvaluan Dollar'), (142, 'TWD - New Taiwan Dollar'), (143, 'TZS - Tanzanian Shilling'), (144, 'UAH - Hryvnia'), (145, 'UGX - Uganda Shilling'), (146, 'USD - US Dollar'), (147, 'UYU - Peso Uruguayo'), (148, 'UZS - Uzbekistan Sum'), (149, 'VES - Bolívar Soberano'), (150, 'VND - Dong'), (151, 'VUV - Vatu'), (152, 'WST - Tala'), (153, 'XAF - CFA Franc BEAC'), (154, 'XCD - East Caribbean Dollar'), (155, 'XOF - CFA Franc BCEAO'), (156, 'XPF - CFP Franc'), (157, 'YER - Yemeni Rial'), (158, 'ZAR - Rand'), (159, 'ZMW - Zambian Kwacha'), (160, 'ZWL - Zimbabwe Dollar')], default=63)),
                ('jenis_rekening', models.CharField(max_length=255)),
                ('status_aktif', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_currency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_transactions', models.CharField(max_length=255)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jenis_transaksi', models.IntegerField(choices=[(0, 'Transfer Tunai'), (1, 'Pembayaran'), (2, 'Tarik Tunai')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'Tidak Diketahui'), (1, 'Aman'), (2, 'Mencurigakan')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ManyToManyField(related_name='users_currency_transaction', to='bank.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created'],
            },
        ),
    ]
