# Generated by Django 5.2.3 on 2025-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_currency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_currency',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nominal',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
